config/routes.rb
Rails.application.routes.draw do
  root to: 'nav_calculation#index'
  resources :nav_calculation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/date_wise_nav.rb
class DateWiseNav < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nav_calculation_controller.rb
include Finance

class NavCalculationController < ApplicationController
  def index
  end

  def show
  end

  def create
  	scheme_name = params[:scheme_name]
  	dates = params[:date]
  	amount = params[:amount]

  	data_schema = []
  	scheme_name.each_with_index do |value, index|
      data_schema << {scheme: value,investment_date: dates[index],amount_invested: amount[index]}
  	end

    scheme_unit_map = {}
    @scheme_current_value_map = {}

    trans = []

    data_schema.each do |data| 
      if(data[:amount_invested].present? && data[:investment_date].present?)
        nav_for_given_date       = DateWiseNav.find_by(scheme_name: data[:scheme],nav_date: Date.parse(data[:investment_date]))&.nav
        if nav_for_given_date.present?
          units_alloted_for_amount = data[:amount_invested].to_f/nav_for_given_date
          if scheme_unit_map.has_key? data[:scheme].to_sym
            new_units = scheme_unit_map[data[:scheme].to_sym] + units_alloted_for_amount
            scheme_unit_map[data[:scheme]] = new_units
          else
            scheme_unit_map[data[:scheme]] = units_alloted_for_amount
          end
          trans << Transaction.new( data[:amount_invested].to_i, date: Time.new(data[:investment_date]))
        end
      end
    end

    @xirr = trans.xirr.apr.to_f.round(2) rescue nil

    scheme_unit_map.each do |scheme,units|
      scheme_last_nav = DateWiseNav.where(scheme_name: scheme).order(nav_date: :desc).first.nav
      @scheme_current_value_map[scheme] = scheme_last_nav*scheme_unit_map[scheme]
    end

    respond_to do |format|
      format.js
      format.json {render json: @scheme_current_value_map}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nav_calculation_helper.rb
module NavCalculationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NavCalculation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nav_calculation/_form.html.erb
<div class="skillsForm">
  <%= label_tag 'scheme_name' %>
  <%= select_tag 'scheme_name[]',options_for_select(DateWiseNav.all.pluck(:scheme_name).uniq) %>

  <%= form.label :date %>
  <%= date_field_tag 'date[]' %>

  <%= label_tag 'amount' %>
  <%= text_field_tag 'amount[]' %>
</div>

app/views/nav_calculation/_nav_details.html.erb
<%scheme_mapping.each do |scheme,nav| %>
<%="#{scheme} => #{nav}"%>
<br/>
<%end%>

<br/>

Xirr: <%=xirr.to_s%>

app/views/nav_calculation/create.js.erb
$('#showOutput').html("<%= j render partial: 'nav_details',locals: {scheme_mapping: @scheme_current_value_map,xirr: @xirr} %>");

app/views/nav_calculation/index.html.erb
<%= form_for :nav_calculation, url: nav_calculation_index_path,remote: true do |form| %>
  <div id="skillSet">
  	<%= render partial: 'form',locals: {form: form} %>
  </div>
  <a href="javascript:;" id="addNewTag">Add New Tag</a>

  <div class="hide" id="new_skills_form" style="display:none;">
	 <%= render partial: 'form', locals: {form: form} %>
  </div>

  <%= form.submit 'get details'  %>
<% end  %>


<div id='showOutput'>
</div>

<script type="text/javascript">
	$(document).ready(function(){
	  $("#addNewTag").click(function(){
	    $("#skillSet").append($("#new_skills_form").html());
	  });
	});
</script>

app/views/nav_calculation/show.html.erb
<h1>NavCalculation#show</h1>
<p>Find me in app/views/nav_calculation/show.html.erb</p>